1、predefined_procedure注册一个 2、全局搜了下，我觉得解决了TypeError: ChainlitEmitter.send_step() missing 1 required positional argument: 'spec' 3、AskUserChoiceMessage的widgets属性，ButtonWidget带data，textReply的第三个参数是widgets列表